name: heallth_report

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: "master"
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: update readme
        env:
          ID: ${{ secrets.ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PUSH_URL: ${{ secrets.PUSH_URL }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          pip install playwright --user
          pip install requests
          python -m playwright install-deps
          python -m playwright install webkit
          python ./main.py